

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mortality_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: mortality_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always